// Generated by Haxe 3.3.0
#ifndef INCLUDED_ComparisonBug
#define INCLUDED_ComparisonBug

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(ComparisonBug)



class HXCPP_CLASS_ATTRIBUTES ComparisonBug_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef ComparisonBug_obj OBJ_;
		ComparisonBug_obj();

	public:
		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="ComparisonBug")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"ComparisonBug"); }
		static hx::ObjectPtr< ComparisonBug_obj > __new();
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~ComparisonBug_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		static void __register();
		::String __ToString() const { return HX_HCSTRING("ComparisonBug","\x4b","\xa3","\x53","\x64"); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_ComparisonBug */ 
