// Generated by Haxe 3.3.0
#include <hxcpp.h>

#ifndef INCLUDED_ComparisonBug
#include <ComparisonBug.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif


void ComparisonBug_obj::__construct(){
            	HX_STACK_FRAME("ComparisonBug","new",0x282a45bd,"ComparisonBug.new","ComparisonBug.hx",14,0xc10a8053)
            	HX_STACK_THIS(this)
            	}

Dynamic ComparisonBug_obj::__CreateEmpty() { return new ComparisonBug_obj; }

hx::ObjectPtr< ComparisonBug_obj > ComparisonBug_obj::__new()
{
	hx::ObjectPtr< ComparisonBug_obj > _hx_result = new ComparisonBug_obj();
	_hx_result->__construct();
	return _hx_result;
}

Dynamic ComparisonBug_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< ComparisonBug_obj > _hx_result = new ComparisonBug_obj();
	_hx_result->__construct();
	return _hx_result;
}

void ComparisonBug_obj::main(){
            	HX_STACK_FRAME("ComparisonBug","main",0xfc26743c,"ComparisonBug.main","ComparisonBug.hx",4,0xc10a8053)
HXLINE(   8)		::haxe::Log_obj::trace(HX_("anus",8b,90,71,40),hx::SourceInfo(HX_("ComparisonBug.hx",53,80,0a,c1),8,HX_("ComparisonBug",4b,a3,53,64),HX_("main",39,38,56,48)));
HXLINE(  11)		::haxe::Log_obj::trace(hx::IsEq( (int)0, ::ComparisonBug_obj::__new() ),hx::SourceInfo(HX_("ComparisonBug.hx",53,80,0a,c1),11,HX_("ComparisonBug",4b,a3,53,64),HX_("main",39,38,56,48)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(ComparisonBug_obj,main,(void))


ComparisonBug_obj::ComparisonBug_obj()
{
}

bool ComparisonBug_obj::__GetStatic(const ::String &inName, Dynamic &outValue, hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#if HXCPP_SCRIPTABLE
static hx::StorageInfo *ComparisonBug_obj_sMemberStorageInfo = 0;
static hx::StaticInfo *ComparisonBug_obj_sStaticStorageInfo = 0;
#endif

static void ComparisonBug_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(ComparisonBug_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void ComparisonBug_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(ComparisonBug_obj::__mClass,"__mClass");
};

#endif

hx::Class ComparisonBug_obj::__mClass;

static ::String ComparisonBug_obj_sStaticFields[] = {
	HX_HCSTRING("main","\x39","\x38","\x56","\x48"),
	::String(null())
};

void ComparisonBug_obj::__register()
{
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("ComparisonBug","\x4b","\xa3","\x53","\x64");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &ComparisonBug_obj::__GetStatic;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = ComparisonBug_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(ComparisonBug_obj_sStaticFields);
	__mClass->mMembers = hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = hx::TCanCast< ComparisonBug_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = ComparisonBug_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ComparisonBug_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ComparisonBug_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

